$(function(){
  //ボタンがクリックされたら文字色変化
  $('#change-color').on('click',function(){
    $('#target').css('color','red');
  });
  //ボタンがクリックされたら文字内容変化
  $('#change-text').on('click',function(){
    $('#target').text('Hello!');
  });
  //ボタンがクリックされたらフェードアウトで文字が消える
  $('#fade-out').on('click',function(){
    $('#target').fadeOut();
  });
  //ボタンがクリックされたらフェードインで文字が現れる
  $('#fade-in').on('click',function(){
    $('#target').fadeIn();
  });
});